### ISSUE TITLE
Broken Example Code for Eink FeatherWing

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_CircuitPython_EPD#11]
Testing bitmap demo code with PID 4128 2.13in eInk Tri-Color FeatherWing and Feather M4 Express. 

- Using circuit python 4.0 beta 6. 

- Library bundle adafruit-circuitpython-bundle-4.x-mpy-20190323. 

Got the following error message in Mu serial console.

`  File "code.py", line 22, in <module>
TypeError: unexpected keyword argument 'sramcs_pin'`

Pins were changed to reflect featherWing. Tested using Feather M4 Express.

```
# create the spi device and pins we will need
spi = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
ecs = digitalio.DigitalInOut(board.D10)
dc = digitalio.DigitalInOut(board.D9)
srcs = digitalio.DigitalInOut(board.D6)    # can be None to use internal memory
rst = digitalio.DigitalInOut(board.D11)    # can be None to not use this pin
busy = digitalio.DigitalInOut(board.D12)   # can be None to not use this pin
```

**Comment by ladyada** [comment]
the library just got updated you can try the mpy's from this release

**Comment by djecken** [comment]
Updated circuit python epd library to latest. Testing the [epd_blinka.py demo code](https://github.com/adafruit/Adafruit_CircuitPython_EPD/blob/master/examples/epd_blinka.py) and missing the "PIL" library – Not seeing that in the bundle.

**Comment by ladyada** [comment]
oh thats for linux you cant use that with feather :)

**Comment by djecken** [comment]
OK. now testing the [edp_bitmap.py](https://github.com/adafruit/Adafruit_CircuitPython_EPD/blob/master/examples/epd_bitmap.py) example code with updated display/pin values. 

Display doesn't update but the code shows fine in mu's serial.

`code.py output:
File opened
Size: 66198
Image offset: 54
Header size: 40
Width: 212
Height: 104
Bit depth: 24
Image OK! Drawing...`

Using these pins for display object

```
spi = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
ecs = digitalio.DigitalInOut(board.D12)
dc = digitalio.DigitalInOut(board.D11)
srcs = digitalio.DigitalInOut(board.D10)
rst = digitalio.DigitalInOut(board.D5)
busy = digitalio.DigitalInOut(board.D4)


display = Adafruit_IL0373(104, 212, spi,
                          cs_pin=ecs, dc_pin=dc, sramcs_pin=srcs,
                          rst_pin=rst, busy_pin=busy)
```

**Comment by ladyada** [comment]
please find me on slack - i think its working fine :)
