### ISSUE TITLE
Example fails with OverflowError:  value must fit in 1 byte(s)

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_EPD#19]
I am using CP 4 rc3.  I was told there was a recent change that checks on assignment for high-order bits truncation.  The EPD library used to do & 0xFF when assigning to a buffer item, but that was removed.  I think it is now really needed.

epd.py lines 131, 132
mcp_sram.py lines 74,75,84,85,113,114 
all need & 0xFF added.

I am ready to fix this, if it is truely a bug.

**Comment by makermelissa** [comment]
Hi. Would you like to submit a PR?

**Comment by mrmcwethy** [comment]
I wlll.

Sent from Yahoo Mail on Android 
 
  On Sun, May 19, 2019 at 3:20 PM, Melissa LeBlanc-Williams<notifications@github.com> wrote:   
Hi. Would you like to submit a PR?

**Comment by mrmcwethy** [comment]
Done
    On Sunday, May 19, 2019, 3:27:35 PM MST, Michael McWethy <mrmcwethy@yahoo.com> wrote:  
 
 I wlll.

Sent from Yahoo Mail on Android 
 
  On Sun, May 19, 2019 at 3:20 PM, Melissa LeBlanc-Williams<notifications@github.com> wrote:   
Hi. Would you like to submit a PR?

**Comment by makermelissa** [comment]
Thanks, I'm testing it. :)

**Comment by makermelissa** [comment]
Fixed with #20.
