### ISSUE TITLE
fill() method does not seem to work after first time eink 1.54 display

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_EPD#21]
I have found that I have to start the program over to clear that screen again.  A method that works is fill_rect(), but I think that fill() should work too.

[testcase.txt](https://github.com/adafruit/Adafruit_CircuitPython_EPD/files/3217497/testcase.txt)

**Comment by dherrada** [comment]
@mrmcwethy Are you referring to the monochrome or tri-color 1.54 eink display?

**Comment by mrmcwethy** [comment]
I have a metro M4 express with the 1.54 monochrome screen.  Also I am using CP 4.0 with latest bundle.

**Comment by mrmcwethy** [comment]
By the way, I am pretty sure that the mcp_sram.erase(() function is not updating the sram as needed.  I change erase to use mcp_sram.write() for each byte and works okay, but slower.

**Comment by dherrada** [comment]
Ok. I'm gonna take a look at this and try to fix it. I'll let you know what I come up with.

**Comment by mrmcwethy** [comment]
This is fixed with release 2.03.
