### ISSUE TITLE
Cannot share the SPI communication lines with the EInk  board 

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_EPD#22]
My setup includes a Airlift breakout board, Eink 1.54 monochrome display board, and Metro M4 Express.  When I connected the standard SPI lines to both the display board and the Airlift board, the Airlift board could not  obtain a WIFI connection.   So I created separate SPI lines for the display board.  Once I had done that, the Airlift board worked as expected.  You would think the problem was with the Airlift board, but no.  The EPD software was keeping the SRAM CS signal low, which cause interference with Airlift SPI signals.    I made a code change which I am happy to release.  In adafruit_epd.py display() method, the self.sram.cs_pin.value is set to false but is not set to True with a monochrome display.  The fix in is a if block at lines 136-154.  _buffer2_size is 0 for monochrome boards, therefore self.sram.cs_pin.value is never set to True and stay False.  Not good.  I added an else: block after 154
`else:
            if self.sram:
                self.sram.cs_pin.value = True
`
The seems to fix the SPI line sharing AND the issue #21.

**Comment by ladyada** [comment]
oh woops, yeah please submit a PR :)

**Comment by ladyada** [comment]
sorry for the delay! do you have bits to do a release?

**Comment by mrmcwethy** [comment]
@ladyada thanks for the merge.  I will look into releasing next.  Its been awhile since  I did one.

**Comment by makermelissa** [comment]
Just let me know if you need any help with releasing. :)

**Comment by mrmcwethy** [comment]
Okay, I tried.  Did I miss something?
Mike
    On Thursday, June 13, 2019, 1:54:26 PM MST, Melissa LeBlanc-Williams <notifications@github.com> wrote:  
 
 
Just let me know if you need any help with releasing. :)

**Comment by makermelissa** [comment]
I like to copy the basic info from the previous release and just update the top line. I went ahead and updated the text to reflect this. Thanks!

**Comment by mrmcwethy** [comment]
Ok, Thanks!
Mike
    On Thursday, June 13, 2019, 5:31:54 PM MST, Melissa LeBlanc-Williams <notifications@github.com> wrote:  
 
 
Closed #22.

**Comment by tannewt** [comment]
FYI the tag should have been `2.0.3` not `2.03` to make sure it's semver which always has three separate numbers. I bumped it to 2.4.0 so the latest is semver again.

**Comment by makermelissa** [comment]
Good catch Scott. I missed that.

**Comment by mrmcwethy** [comment]
Darn it.  So did I.  Thanks scott!

Sent from Yahoo Mail on Android 
 
  On Fri, Jun 14, 2019 at 11:39 AM, Melissa LeBlanc-Williams<notifications@github.com> wrote:   
Good catch Scott. I missed that.
