### ISSUE TITLE
Can't find lut time definitions.

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/Adafruit_CircuitPython_EPD#5]
i know the display is advertised for partial refresh but i though i would give it a try. i'm looking through the code and i cant find where  the timing for the page changing is. i tried chafing the lut_bb,wb,bw2,ww etc in .py and allot of  other parameters i just can;t find any comments that say where the time in-between number of inverse flashes what refreshing display is. i checked both files and oi just don't see it in comments or code.

thanks for any and all help,
TG-Techie

**Comment by ladyada** [comment]
some displays have the LUT built into the display, which is good becuase the LUT should be customized per manufacturing run. Some displays have it as a bytearray - check the SSD chips to see a LUT-loading example. compare to the arduino code :) https://github.com/adafruit/Adafruit_EPD
