### ISSUE TITLE
Using height for width of RAM in x direction

### ISSUE THREAD

**Issue by matiasilva** [adafruit/Adafruit_CircuitPython_EPD#54]
Hello,

Came across [this line](https://github.com/adafruit/Adafruit_CircuitPython_EPD/blob/042a433ce270409f4c93fc86568f0af14fcca645/adafruit_epd/ssd1681.py#L133) that sets the "width" of the onboard SSD1681 RAM but was wondering why it uses the height of the board and not the width? This is a 200x200 display, so in effect they are the same but I may be wrong here. 

Thanks!

**Comment by ladyada** [comment]
EPDs are not well documented & this code works so far. if you find a situation/epd that this doesnt work for, that you know for a fact is SSD1681 please re-open :)
