### ISSUE TITLE
2.7" display driver

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_EPD#8]
its not the same chip!

**Comment by tannewt** [comment]
What chip is it? I think we should have separate repos for different driver chips.

**Comment by ladyada** [comment]
theres 8 or so different chipsets. i guess i could pull it apart, at the time we were mimicing RGBDisplay.

**Comment by tannewt** [comment]
I prefer apart because it then matches all of the other sensor libraries.

**Comment by ladyada** [comment]
added it latest PR
